"""

Quando você executa chamadas assíncronas dentro de blocos try...except, deve usar await para aguardar a conclusão dessas chamadas. Isso permite que você capture e trate exceções assíncronas 


"""