"""
Exceções assíncronas em Python são usadas em código assíncrono, ou seja onde várias operações podem ocorrer simultaneamente
"""
